#!/usr/bin/env python3
"""Intraday monitor for the latest A-share pick.

Reads state/latest_pick.json generated by the evening review workflow. During
A-share trading hours, checks live quote data and pushes one-time alerts when
the previous pick reaches the planned observation zones.
"""

from __future__ import annotations

import datetime as dt
import json
import os
import urllib.request
from pathlib import Path
from typing import Any


HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36"
    ),
    "Referer": "https://quote.eastmoney.com/",
}

STATE_DIR = Path("state")
LATEST_PICK_PATH = STATE_DIR / "latest_pick.json"
ALERT_STATE_PATH = STATE_DIR / "intraday_alerts.json"


def beijing_now() -> dt.datetime:
    return dt.datetime.now(dt.timezone(dt.timedelta(hours=8)))


def is_trading_time(now: dt.datetime) -> bool:
    if now.weekday() >= 5:
        return False
    minutes = now.hour * 60 + now.minute
    return (9 * 60 + 25 <= minutes <= 11 * 60 + 30) or (13 * 60 <= minutes <= 15 * 60)


def http_json(url: str, *, method: str = "GET", payload: dict[str, Any] | None = None) -> dict[str, Any]:
    data = None
    headers = dict(HEADERS)
    if payload is not None:
        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8", errors="replace"))


def safe_float(value: Any) -> float | None:
    try:
        if value in (None, "-", ""):
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def stock_sec_id(code: str) -> str:
    return f"1.{code}" if code.startswith(("6", "9")) else f"0.{code}"


def fetch_quote(code: str) -> dict[str, Any]:
    fields = "f43,f44,f45,f46,f47,f48,f57,f58,f60,f169,f170"
    url = f"https://push2.eastmoney.com/api/qt/stock/get?secid={stock_sec_id(code)}&fields={fields}"
    data = http_json(url).get("data") or {}
    price = safe_float(data.get("f43"))
    high = safe_float(data.get("f44"))
    low = safe_float(data.get("f45"))
    open_price = safe_float(data.get("f46"))
    prev = safe_float(data.get("f60"))
    change = safe_float(data.get("f169"))
    pct = safe_float(data.get("f170"))
    amount = safe_float(data.get("f48"))
    return {
        "code": data.get("f57") or code,
        "name": data.get("f58") or "",
        "price": round(price / 100, 2) if price is not None else None,
        "high": round(high / 100, 2) if high is not None else None,
        "low": round(low / 100, 2) if low is not None else None,
        "open": round(open_price / 100, 2) if open_price is not None else None,
        "prev_close": round(prev / 100, 2) if prev is not None else None,
        "change": round(change / 100, 2) if change is not None else None,
        "pct": round(pct / 100, 2) if pct is not None else None,
        "amount_yi": round(amount / 100_000_000, 2) if amount is not None else None,
    }


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, value: Any) -> None:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")


def determine_alert(latest: dict[str, Any], quote: dict[str, Any]) -> tuple[str, str, str] | None:
    price = quote.get("price")
    pct = quote.get("pct")
    if price is None:
        return None
    plan = latest.get("buy_plan") or {}
    pick = latest.get("pick") or {}
    name = quote.get("name") or pick.get("name") or ""
    code = quote.get("code") or pick.get("code") or ""

    hard_stop = plan.get("hard_stop_below")
    stop = plan.get("stop_below")
    no_chase = plan.get("no_chase_above")
    pullback_min = plan.get("pullback_min")
    pullback_max = plan.get("pullback_max")
    strong_min = plan.get("strong_min")
    strong_max = plan.get("strong_max")

    if hard_stop is not None and price <= hard_stop:
        return (
            "hard_stop",
            f"{name} {code} 跌破强风控线",
            "暂不按原买入观察计划执行，短线资金可能明显松动。",
        )
    if stop is not None and price < stop:
        return (
            "stop",
            f"{name} {code} 跌破短线风控线",
            "暂不执行原买入观察计划，等待重新企稳。",
        )
    if no_chase is not None and price >= no_chase:
        return (
            "no_chase",
            f"{name} {code} 进入不建议追高区",
            "涨幅/位置偏高，不适合按原计划追高。",
        )
    if pullback_min is not None and pullback_max is not None and pullback_min <= price <= pullback_max:
        if pct is None or pct > -5:
            return (
                "pullback_buy_zone",
                f"{name} {code} 进入回踩观察买区",
                "可观察承接，若分时企稳且成交不弱，可作为买入观察点。",
            )
    if strong_min is not None and strong_max is not None and strong_min <= price <= strong_max:
        if pct is None or pct >= -0.5:
            return (
                "strong_buy_zone",
                f"{name} {code} 进入强势确认区",
                "只适合轻仓观察，需确认放量和分时承接，不宜盲目追高。",
            )
    return None


def push_wxpusher(content: str, summary: str) -> dict[str, Any]:
    app_token = os.environ.get("WXPUSHER_APP_TOKEN")
    uids_raw = os.environ.get("WXPUSHER_UIDS", "")
    uids = [item.strip() for item in uids_raw.split(",") if item.strip()]
    if not app_token or not uids:
        return {"ok": False, "reason": "missing WXPUSHER_APP_TOKEN or WXPUSHER_UIDS"}
    return http_json(
        "https://wxpusher.zjiecode.com/api/send/message",
        method="POST",
        payload={
            "appToken": app_token,
            "uids": uids,
            "summary": summary,
            "content": content,
            "contentType": 1,
        },
    )


def main() -> int:
    now = beijing_now()
    if not is_trading_time(now):
        print(f"非交易时段：{now.isoformat(timespec='seconds')}")
        return 0
    latest = load_json(LATEST_PICK_PATH, None)
    if not latest:
        print("未找到 state/latest_pick.json，无法监控。")
        return 0

    pick = latest.get("pick") or {}
    code = pick.get("code")
    if not code:
        print("latest_pick 中没有股票代码，无法监控。")
        return 0

    rec_date = latest.get("recommendation_date")
    if rec_date == now.strftime("%Y-%m-%d"):
        print("候选是今天刚生成的，等待下一个交易日再盘中监控。")
        return 0

    quote = fetch_quote(code)
    alert = determine_alert(latest, quote)
    if not alert:
        print(f"未触发：{quote.get('name')} {code} 当前价 {quote.get('price')}，涨跌幅 {quote.get('pct')}%，继续监控。")
        return 0

    alert_key, title, action = alert
    day_key = now.strftime("%Y-%m-%d")
    alert_state = load_json(ALERT_STATE_PATH, {})
    sent_keys = set(alert_state.get(day_key, []))
    compound_key = f"{code}:{alert_key}"
    if compound_key in sent_keys:
        print(f"已提醒过：{compound_key}")
        return 0

    plan = latest.get("buy_plan") or {}
    content = "\n".join(
        [
            f"触发提醒：{title}",
            f"时间：{now.strftime('%Y-%m-%d %H:%M:%S')} 北京时间",
            f"当前价：{quote.get('price')}，涨跌幅：{quote.get('pct')}%，成交额约：{quote.get('amount_yi')} 亿",
            f"触发条件：{alert_key}",
            f"建议动作：{action}",
            (
                "观察区间："
                f"回踩 {plan.get('pullback_min')}-{plan.get('pullback_max')}；"
                f"强势 {plan.get('strong_min')}-{plan.get('strong_max')}；"
                f"不追高 {plan.get('no_chase_above')} 以上；"
                f"风控 {plan.get('stop_below')} / {plan.get('hard_stop_below')}"
            ),
            "风险提示：若大盘或所属板块快速转弱，信号失效概率会上升。",
            "仅供研究观察，不构成投资建议，不承诺收益。",
        ]
    )
    summary_price = quote.get("price")
    summary_pct = quote.get("pct")
    summary = f"{pick.get('name')} {code} 盘中提醒"
    if summary_price is not None:
        summary += f" 当前价 {summary_price}"
    if summary_pct is not None:
        summary += f" 涨跌幅 {summary_pct}%"

    result = push_wxpusher(content, summary)
    if result.get("code") == 1000:
        sent_keys.add(compound_key)
        alert_state[day_key] = sorted(sent_keys)
        save_json(ALERT_STATE_PATH, alert_state)
    print(content)
    print("\n--- WxPusher result ---")
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result.get("code") == 1000 else 1


if __name__ == "__main__":
    raise SystemExit(main())
